### ISSUE TITLE
Butterfly UI does not load graph and unable to select traces

### ISSUE THREAD

**Issue by TomPallister** [ButterflyAPM/butterfly#24]
Hi thanks for your work on this project it is very cool!

I get the following error when using Butterfly!

ERROR Error: Uncaught (in promise): TypeError: Invalid Time: 13/02/2018 14:04:00 +00:00
TypeError: Invalid Time: 13/02/2018 14:04:00 +00:00

Screenshot..

![image](https://user-images.githubusercontent.com/5716716/36153847-89614bb2-10c7-11e8-97c5-9ad4699ffb5b.png)

I am using Chrome and my local time is GMT.

If I have time I will look into this myself and submit a PR.

**Comment by liuhaoyang** [comment]
I will fix it in the next version. https://github.com/liuhaoyang/butterfly/commit/f3e2766687e33a6023fa93e137de1a90bb30ac9e

**Comment by TomPallister** [comment]
@liuhaoyang thank you :)

**Comment by liuhaoyang** [comment]
I have fixed it in [butterfly-web-preview-0.0.8](https://github.com/ButterflyAPM/butterfly/releases/tag/preview-0.0.8)
